src/accounts/urls.py
from django.urls import path

from .views import SignUpView, UserDetailView, UserUpdate, UserDelete, UserFollowingsView, UserInterestedView

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('<str:slug>', UserDetailView.as_view(), name='details'),
    path('<str:slug>/edit', UserUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', UserDelete.as_view(), name='delete'),
    path('<str:slug>/followings', UserFollowingsView.as_view(), name='followings'),
    path('<str:slug>/interested', UserInterestedView.as_view(), name='interested'),
]

src/artists/urls.py
from django.urls import path
from artists.views import ArtistsList, ArtistCreate, ArtistCreateSpotifyFollowings, ArtistFollowSpotifyFollowings, ArtistDelete, ArtistDetail, ArtistUpdate, ArtistFollowingView

app_name = "artists"

urlpatterns = [
    path('', ArtistsList.as_view(), name='list'),
    path('create/', ArtistCreate, name='create'),
    path('create/spotify_followings/', ArtistCreateSpotifyFollowings, name='create_spotify_followings'),
    path('follow/spotify_followings/', ArtistFollowSpotifyFollowings, name='follow_spotify_followings'),
    path('<str:slug>', ArtistDetail.as_view(), name='artist'),
    path('<str:slug>/edit', ArtistUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', ArtistDelete.as_view(), name='delete'),
    path('<str:slug>/follow', ArtistFollowingView, name='follow'),
]

src/blog/urls.py
from django.urls import path
from blog.views import BlogPostList, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete

app_name = "blog"

urlpatterns = [
    path('', BlogPostList.as_view(), name='list'),
    path('create/', BlogPostCreate.as_view(), name='create'),
    path('<str:slug>', BlogPostDetail.as_view(), name='post'),
    path('<str:slug>/edit', BlogPostUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', BlogPostDelete.as_view(), name='delete'),
]

src/comments/urls.py
from django.urls import path

from comments.views import CommentView

app_name = "comments"

urlpatterns = [
    path('<str:type>/<str:slug>/comment', CommentView, name='comment'),
]

src/events/urls.py
from django.urls import path
from events.views import EventInterestedView, EventsList, EventCreate, EventUpdate, EventDetail, EventDelete

app_name = "events"

urlpatterns = [
    path('', EventsList.as_view(), name='list'),
    path('create/', EventCreate.as_view(), name='create'),
    path('<str:slug>', EventDetail.as_view(), name='event'),
    path('<str:slug>/edit', EventUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', EventDelete.as_view(), name='delete'),
    path('<str:slug>/interested', EventInterestedView, name='interested'),
]

src/nightlife/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from artists.views import spotify_callback
from events import views
from events.views import Home, Search

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('events/', include('events.urls')),
    path('artists/', include('artists.urls')),
    path('blog/', include('blog.urls')),
    path('comments/', include('comments.urls')),
    #path('tags/', include('tags.urls')),
    path('search/', views.Search, name='search'),
    path('callback/', spotify_callback, name='spotify_callback'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/comments/models.py
from django.conf import settings
from django.db import models

# Create your models here.
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_on"]
        verbose_name = "Commentaire"

    def __str__(self):
        return self.comment

src/comments/forms.py
from django import forms

from comments.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

src/comments/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required

from artists.models import Artist
from blog.models import BlogPost
from comments.forms import CommentForm
from events.models import Event


# Create your views here.
@login_required
def CommentView(request, slug, type):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if type == "event": model = get_object_or_404(Event, slug=slug)
        elif type == "artist": model = get_object_or_404(Artist, slug=slug)
        elif type == "blogpost": model = get_object_or_404(BlogPost, slug=slug)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.model = model
            new_comment.comment = form.cleaned_data.get('comment')
            form.save()
            model.comments.add(new_comment)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = CommentForm()

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    {% block title %}

    {% endblock %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/forms.js' %}"></script>
    <script src="{% static 'js/search_bar.js' %}"></script>
    <script src="{% static 'js/scroll_to_top.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
  </head>
  <body>
    {% include 'header.html' %}
    {% block content %}

    {% endblock %}
    <!-- Back to top button -->
    <button type="button" class="btn btn-secondary btn-lg" id="btn-back-to-top"><i class="bi bi-arrow-up"></i></button>
  </body>
</html>

src/templates/comments.html
{% load static %}
<div class="row row-padding align-items-center">
  <div class="col-2">
    <a href="{% url 'accounts:details' slug=comment.user|slugify %}">
      <div class="row container-circle">
        <div class="circle">
          {% if comment.user.thumbnail %}
            <img src="{{ comment.user.thumbnail.url }}" alt="{{ comment.user }}" />
          {% else %}
            <img src="{% get_media_prefix %}commons/users/user.png" alt="{{ comment.user }}" />
          {% endif %}
        </div>
      </div>
    </a>
  </div>
  <div class="col">
    <div class="row row-padding name">
      <a href="{% url 'accounts:details' slug=comment.user|slugify %}"><h5>{{ comment.user }}</h5></a>
      <p class="text-time">Le {{ comment.created_on }}</p>
    </div>
    <div class="row row-padding bg-white">
      <p class="fst-italic">{{ comment.comment|linebreaks }}</p>
    </div>
  </div>
</div>

src/templates/header.html
{% load static %}

<header class="p-3 bg-dark navbar-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a class="navbar-brand d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none" href="{% url 'home' %}">Nightlife</a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href={% url 'events:list' %} class="nav-link px-2 text-white">Les évènements</a></li>
        <li><a href={% url 'artists:list' %} class="nav-link px-2 text-white">Les artistes</a></li>
        <li><a href={% url 'blog:list' %} class="nav-link px-2 text-white">Le blog</a></li>
        <li><a class="nav-link px-2 text-white" href="{% url 'events:create' %}">J'organise un évènement !</a></li>
      </ul>
    

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" method="POST" action="{% url 'search' %}">
        {% csrf_token %}
        <div class="search-container">
          <input type="text" class="form-control search-input" placeholder="Rechercher..." name="search_query"/>
          <i class="bi bi-search search-icon"></i>
        </div>
      </form>

      

      {% if request.user.is_authenticated %}
        <div class="dropdown">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <div class="container-circle container-circle-navbar">
              <div class="circle">
            {% if request.user.thumbnail %}
              <img src="{{ user.thumbnail.url }}" alt="{{ request.user }}"/>
            {% else %}
              <img src="{% get_media_prefix %}commons/users/user.png" alt="{{ request.user }}"/>
            {% endif %}
              </div>
            </div>
          </a>
          <ul class="dropdown-menu text-small" style="">
            <li class="dropdown-header">👋 {{ request.user }}</li>
            <li>
              <a class="dropdown-item" href="{% url 'accounts:details' slug=user.slug %}">Mon profil</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'accounts:interested' slug=user.slug %}">Mes évènements</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'accounts:followings' slug=user.slug %}">Mes artistes favoris</a>
            </li>
            <li>
              <hr class="dropdown-divider" />
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'logout' %}">Me déconnecter</a>
            </li>
          </ul>
        </div>
      {% else %}
        <div class="text-end">
          <a class="btn btn-light" href="{% url 'login' %}" role="button">Me connecter / S'inscrire</a>
        </div>
      {% endif %}
    </div>
  </div>
</header>