src/accounts/urls.py
from django.urls import path

from .views import SignUpView, UserDetailView, UserUpdate, UserDelete, UserFollowingsView, UserInterestedView

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('<str:slug>', UserDetailView.as_view(), name='details'),
    path('<str:slug>/edit', UserUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', UserDelete.as_view(), name='delete'),
    path('<str:slug>/followings', UserFollowingsView.as_view(), name='followings'),
    path('<str:slug>/interested', UserInterestedView.as_view(), name='interested'),
]

src/blog/urls.py
from django.urls import path
from blog.views import BlogPostList, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete

app_name = "blog"

urlpatterns = [
    path('', BlogPostList.as_view(), name='list'),
    path('create/', BlogPostCreate.as_view(), name='create'),
    path('<str:slug>', BlogPostDetail.as_view(), name='post'),
    path('<str:slug>/edit', BlogPostUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', BlogPostDelete.as_view(), name='delete'),
]

src/comments/urls.py
from django.urls import path

from comments.views import CommentView

app_name = "comments"

urlpatterns = [
    path('<str:type>/<str:slug>/comment', CommentView, name='comment'),
]

src/nightlife/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from artists.views import spotify_callback
from events import views
from events.views import Home, Search

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('events/', include('events.urls')),
    path('artists/', include('artists.urls')),
    path('blog/', include('blog.urls')),
    path('comments/', include('comments.urls')),
    #path('tags/', include('tags.urls')),
    path('search/', views.Search, name='search'),
    path('callback/', spotify_callback, name='spotify_callback'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
import datetime
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from datetime import date
import readtime
from artists.models import Artist
from events.models import Comment, Event, Tag
from nightlife.methods import PathAndRename

# Create your models here.
class BlogPost(models.Model):
    path_and_rename = PathAndRename("blog/")
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre de l'article")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    created_on = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="author")
    is_featured = models.BooleanField(default=False, verbose_name="Présent sur la page d'accueil")
    summary = models.CharField(max_length=255, blank=True, null=True, verbose_name="Sommaire")
    content = models.TextField(blank=True, verbose_name="Contenu")
    thumbnail = models.ImageField(blank=True, upload_to=path_and_rename)
    tags = models.ManyToManyField(Tag, related_name='blogpost_tags')
    related_event = models.ForeignKey(Event, on_delete=models.SET_NULL, related_name='related_event', null=True, blank=True,  verbose_name="Évènement lié")
    related_artists = models.ManyToManyField(Artist, related_name='related_artists', blank=True, verbose_name="Artistes liés")
    comments = models.ManyToManyField(Comment, related_name='blogpost_comments', blank=True)


    class Meta:
        ordering = ["-created_on"]
        verbose_name = "Article"

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        return super().save(*args, **kwargs)
    
    @property
    def is_created_on_past_due(self):
        return date.today() > self.created_on.date()
    
    @property
    def is_last_updated_past_due(self):
        return date.today() > self.last_updated.date()
    
    def get_readtime(self):
      result = readtime.of_text(self.content)
      return result.text
    
    #Définir la redirection
    def get_absolute_url(self):
        return reverse("blog:post", kwargs={"slug": self.slug})

src/blog/views.py
import datetime
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template.defaultfilters import slugify
from django.db.models import Count

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from blog.models import BlogPost
from comments.forms import CommentForm


class BlogPostList(ListView):
    model = BlogPost
    context_object_name = "posts"
    template_name = "blog/blog_list.html"

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-created_on')

        return queryset.filter(published=True)

@method_decorator(login_required, name="dispatch")
class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "blog/blogpost_create.html"
    fields = ['title', 'thumbnail', 'tags', 'summary', 'content', 'published', 'is_featured', 'related_event', 'related_artists']

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user
            
        form.instance.created_on = datetime.datetime.now()
            
        return super().form_valid(form)

@method_decorator(login_required, name="dispatch")
class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = "blog/blogpost_edit.html"
    context_object_name = "post"
    fields = ['title', 'thumbnail', 'tags', 'summary', 'content', 'published', 'is_featured', 'related_event', 'related_artists']

class BlogPostDetail(DetailView):
    model = BlogPost
    template_name = "blog/blogpost_detail.html"
    context_object_name = "post"

@method_decorator(login_required, name="dispatch")
class BlogPostDelete(DeleteView):
    model = BlogPost
    context_object_name = "post"
    success_url = reverse_lazy("blog:list")

src/blog/templates/blog/blogpost_cards.html
<div class="col margin-bottom">
  <div class="card h-100">
    {% if post.thumbnail %}
      <a href="{% url 'blog:post' slug=post.slug %}"><img src="{{ post.thumbnail.url }}" class="card-img-top img-fluid" alt="{{ post.title }}" /></a>
    {% else %}
      <a href="{% url 'blog:post' slug=post.slug %}"><div class="card-img-top img-fluid"></div></a>
    {% endif %}
    <div class="card-body">
      <div class="row">
        <div class="col">
          <div class="headline">
            <a href="{% url 'blog:post' slug=post.slug %}"><h5 class="card-title">{{ post.title|title }}</h5></a>
          </div>
        </div>
      </div>
      <p class="card-text">{{ event.location }}</p>
      <p class="card-text">
        {% if article.summary %}
          <small class="text-body-secondary">{{ post.summary|truncatewords_html:20 }}</small>
        {% else %}
          <small class="text-body-secondary">{{ post.content|truncatewords_html:20 }}</small>
        {% endif %}
      </p>
      {% if post.tags %}
        {% for tag in post.tags.all %}
          <span class="badge rounded-pill">{{ tag.name }}</span>
        {% endfor %}
      {% endif %}
    </div>
  </div>
</div>

src/blog/templates/blog/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  <title>Supprimer: {{ event.title }}</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'blog:list' %}">Le blog</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'blog:post' slug=post.slug %}">{{ post.title }}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Supprimer</li>
      </ol>
    </nav>
  </div>

  <div class="container">
    <div class="row margin-bottom text-center">
      <h1 class="text-center">Supprimer "{{ post.title }}"</h1>
    </div>

    <div class="row row-padding col-8 mx-auto text-center">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Êtes-vous sûr de vouloir supprimer "{{ post.title }}" ?</h3>
        <div class="row">{{ form }}</div>
        <div class="row row-padding">
          <input type="submit" value='Supprimer /"{{ post.title }}"' class="btn btn-danger" />
        </div>
      </form>
    </div>
  </div>
{% endblock %}

src/blog/templates/blog/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
  <title>Créer un article</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'blog:list' %}">Le blog</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Créer un article</li>
      </ol>
    </nav>
  </div>
  <div class="container">
    <div class="row margin-bottom text-center">
      <h1>Créer un article</h1>
    </div>

    <div class="row row-padding col-8 mx-auto">
      <div class="col">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">{{ form }}</div>
          <div class="row row-padding">
            <input type="submit" role="button" value="Créer" class="btn btn-submit btn-light" />
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/blog/templates/blog/blogpost_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>{{ post.title }}</title>
{% endblock %}

{% block content %}
  <div class="container-fluid">
    {% if post.thumbnail %}
      <div class="row img-bg" style="background:url('{{ post.thumbnail.url }}'"></div>
    {% endif %}
  </div>

  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'blog:list' %}">Le blog</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">{{ post.title }}</li>
      </ol>
    </nav>
  </div>

  <div class="container">
    <div class="row margin-bottom text-center">
      <h1>{{ post.title|upper }}</h1>
      <span>
        <p>
          Par <a href="{% url 'accounts:details' slug=post.author|slugify %}">{{ post.author }}</a> <small>| <i class="bi bi-calendar-event"></i> {{ post.created_on|date:'d N Y' }}</small>
          {% if post.created_on != post.last_updated %}
            <small>
              <i>
                (Mis à jour :{% if post.is_last_updated_past_due %}
                  le {{ post.last_updated|date:'d N à H:i' }})
                {% else %}
                  à {{ post.last_updated|date:'H:i' }})
                {% endif %}
              </i>
              - <i class="bi bi-clock"></i> Temps de lecture : {{ post.get_readtime }}
            </small>
          {% endif %}
        </p>
      </span>
    </div>

    <div class="row row-padding">
      <div class="col d-grid">
        <a class="btn btn-light" href="{% url 'blog:edit' slug=post.slug %}" role="button">Éditer</a>
      </div>
      <div class="col d-grid">
        <a class="btn btn-outline-danger" href="{% url 'blog:delete' slug=post.slug %}" role="button">Supprimer</a>
      </div>
    </div>

    <div class="row row-padding">
      {% if post.tags %}
        <div class="margin-bottom">
          <small><i class="bi bi-tags-fill"></i> Tags :</small>
          <h5>
            {% for tag in post.tags.all %}
              <span class="badge rounded-pill">{{ tag.name }}</span>
            {% endfor %}
          </h5>
        </div>
      {% endif %}
      <p class="justify">{{ post.content|safe|linebreaksbr }}</p>
    </div>
    <div class="row row-padding align-items-center">
      <div class="col-9">
        <div class="row row-padding name float-end">
          <a href="{% url 'accounts:details' slug=post.author|slugify %}"><h3>{{ post.author }}</h3></a>
        </div>
        <div class="row row-padding float-end">
          <p class="fst-italic">"{{ post.author.biography }}"</p>
        </div>
      </div>
      <div class="col-3">
        <a href="{% url 'accounts:details' slug=post.author|slugify %}">
          <div class="row container-circle">
            <div class="circle">
              {% if post.author.thumbnail %}
                <img src="{{ post.author.thumbnail.url }}" alt="{{ post.author }}" />
              {% else %}
                <img src="{% get_media_prefix %}commons/users/user.png" alt="{{ post.author }}" />
              {% endif %}
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
  {% if post.related_event %}
    <div class="container-fluid bg-light">
      <div class="container container-section">
        <div class="row row-padding">
          <h1>Évènement lié</h1>
        </div>
        <div class="row row-padding row-cols-1 row-cols-sm-2 row-cols-md-4">
          {% include 'events/event_cards.html' with event=post.related_event %}
        </div>
      </div>
    </div>
  {% endif %}

  {% if post.related_artists %}
    <div class="container-fluid">
      <div class="container container-section">
        <div class="row row-padding">
          <h1>Artiste(s) lié(s)</h1>
        </div>
        <div class="row row-padding row-cols-2 row-cols-lg-5 g-2 g-lg-3">
          {% for artist in post.related_artists.all %}
            {% include 'artists/artist_cards.html' %}
          {% endfor %}
        </div>
      </div>
    </div>
  {% endif %}
  <div class="container-fluid bg-light">
    <div class="container container-section">
      <div class="row">
        <h1>Les commentaires</h1>
        <div class="row row-padding">
          <form action="{% url 'comments:comment' slug=post.slug type='blogpost' %}" method="POST">
            {% csrf_token %}
            <div class="form-floating">
              <textarea class="form-control" placeholder="Laisser un commentaire" id="floatingTextarea2" style="height: 100px" name="comment"></textarea>
              <label for="floatingTextarea2">Laisser un commentaire</label>
            </div>
            <button type="submit" class="btn btn-light">Envoyer</button>
          </form>
        </div>
        {% if post.comments %}
          {% for comment in post.comments.all %}
            {% include 'comments.html' %}
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

src/blog/templates/blog/blogpost_edit.html
{% extends 'base.html' %}

{% block title %}
  <title>Editer {{ post.title }}</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'blog:list' %}">Le blog</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'blog:post' slug=post.slug %}">{{ post.title|title }}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Editer</li>
      </ol>
    </nav>
  </div>
  <div class="container">
    <div class="row margin-bottom text-center">
      <h1>{{ post.title }}</h1>
    </div>

    <div class="row row-padding col-8 mx-auto">
      <div class="col">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">{{ form }}</div>
          <div class="row row-padding">
            <input type="submit" role="button" value="Créer" class="btn btn-submit btn-light" />
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/blog/templates/blog/blogpost_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>Le blog</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Le blog</li>
      </ol>
    </nav>
  </div>

  <div class="container">
    <div class="row margin-bottom text-center">
      <h1>Le blog</h1>
    </div>
    {% if posts %}
      <div class="row row-padding margin-bottom">
        <h5>Derniers articles</h5>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">
          {% for post in posts|slice:4 %}
            {% include 'blog/blogpost_cards.html' %}
          {% endfor %}
        </div>
      </div>
      <div class="row margin-bottom">
        <h5>Toute l'actualité</h5>

        <table class="table table-hover">
          <tbody>
            {% for post in posts %}
              <tr>
                <th scope="row">
                  <i class="bi bi-clock"></i>
                  {% if post.is_created_on_past_due %}
                    {{ post.created_on|date:'d N H:i' }}
                  {% else %}
                    {{ post.created_on|date:'H:i' }}
                  {% endif %}
                </th>
                <td>
                  <a href="{% url 'blog:post' slug=post.slug %}">{{ post.title }}</a>
                </td>
                {% if post.tags %}
                  <td>
                    {% for tag in post.tags.all %}
                      <span class="badge rounded-pill">{{ tag.name }}</span>
                    {% endfor %}
                  </td>
                {% endif %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <div class="col">
        <div class="row row-padding text-center">
          <h2>Pas d'articles pour le moment !</h2>
        </div>
      </div>
    {% endif %}
    <div class="row row-padding col-6 mx-auto">
      <a class="btn btn-light" href="{% url 'blog:create' %}" role="button">Ajouter un article</a>
    </div>
  </div>
{% endblock %}