src/artists/urls.py
from django.urls import path
from artists.views import ArtistsList, ArtistCreate, ArtistCreateSpotifyFollowings, ArtistFollowSpotifyFollowings, ArtistDelete, ArtistDetail, ArtistUpdate, ArtistFollowingView

app_name = "artists"

urlpatterns = [
    path('', ArtistsList.as_view(), name='list'),
    path('create/', ArtistCreate, name='create'),
    path('create/spotify_followings/', ArtistCreateSpotifyFollowings, name='create_spotify_followings'),
    path('follow/spotify_followings/', ArtistFollowSpotifyFollowings, name='follow_spotify_followings'),
    path('<str:slug>', ArtistDetail.as_view(), name='artist'),
    path('<str:slug>/edit', ArtistUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', ArtistDelete.as_view(), name='delete'),
    path('<str:slug>/follow', ArtistFollowingView, name='follow'),
]

src/blog/urls.py
from django.urls import path
from blog.views import BlogPostList, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete

app_name = "blog"

urlpatterns = [
    path('', BlogPostList.as_view(), name='list'),
    path('create/', BlogPostCreate.as_view(), name='create'),
    path('<str:slug>', BlogPostDetail.as_view(), name='post'),
    path('<str:slug>/edit', BlogPostUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', BlogPostDelete.as_view(), name='delete'),
]

src/comments/urls.py
from django.urls import path

from comments.views import CommentView

app_name = "comments"

urlpatterns = [
    path('<str:type>/<str:slug>/comment', CommentView, name='comment'),
]

src/nightlife/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from artists.views import spotify_callback
from events import views
from events.views import Home, Search

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('events/', include('events.urls')),
    path('artists/', include('artists.urls')),
    path('blog/', include('blog.urls')),
    path('comments/', include('comments.urls')),
    #path('tags/', include('tags.urls')),
    path('search/', views.Search, name='search'),
    path('callback/', spotify_callback, name='spotify_callback'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/artists/models.py
import datetime
from django.conf import settings
from django.db import models
from django.forms import ValidationError
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from comments.models import Comment
from nightlife.methods import PathAndRename
from tags.models import Tag

# Create your models here.
class Artist(models.Model):
    path_and_rename = PathAndRename("artists/")
    
    name = models.CharField(max_length=255, unique=True, verbose_name="Nom de l'artiste")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    created_on = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    is_sponsored = models.BooleanField(default=False, verbose_name="Sponsorisé")
    biography = models.TextField(blank=True, verbose_name="Biographie")
    thumbnail = models.ImageField(blank=True, upload_to=path_and_rename)
    spotify = models.CharField(max_length=255, blank=True)
    soundcloud = models.URLField(max_length=255, blank=True)
    instagram = models.URLField(max_length=255, blank=True)
    facebook = models.URLField(max_length=255, blank=True)
    playlist = models.CharField(max_length=255, blank=True)
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="fan")
    tags = models.ManyToManyField(Tag, related_name='artist_tags')
    comments = models.ManyToManyField(Comment, related_name='artist_comments', blank=True)

    class Meta:
        ordering = ["name"]
        verbose_name = "Artiste"

    def __str__(self):
        return self.name
    
    def clean(self):
        #Lancer le contrôle de la présence de l'artiste que sur le create
        if not self.pk:
            if Artist.objects.filter(name=self.name).exists():
                raise ValidationError({'name': _('L\'artiste existe déjà.')})
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        return super().save(*args, **kwargs)
    
    #Définir la redirection
    def get_absolute_url(self):
        return reverse("artists:artist", kwargs={"slug": self.slug})
    
    def total_followers(self):
        return self.followers.count()

src/artists/forms.py
from django import forms

from artists.models import Artist

class ArtistCreateForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ["name", "biography",]

src/artists/views.py
from django.utils import timezone
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template.defaultfilters import slugify
from django.core.files.base import ContentFile

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
import requests

from artists.forms import ArtistCreateForm
from artists.models import Artist
from events.models import Event, Tag
from nightlife.spotify_methods import get_tokens, spotify_search, get_authorization_url, is_user_connected, user_get_followed_artists
    
# Variables globales pour stocker l'adresse avant redirection
REFERER = None

# Ajoutez cette vue pour gérer le callback
@login_required
def spotify_callback(request):
    global REFERER
    code = request.GET.get('code')

    if code:
        access_token, refresh_token = get_tokens(code)
        if access_token:
            # Stockez les jetons dans la session ou la base de données
            request.session['access_token'] = access_token
            request.session['refresh_token'] = refresh_token
            return HttpResponseRedirect(REFERER)
        
    return render(request, 'artists/error.html', {'message': 'Erreur lors de l\'authentification avec Spotify.'})
    
@login_required
def ArtistCreate(request):
    if request.method == "POST":
        form = ArtistCreateForm(request.POST)
        if form.is_valid():
            if not is_user_connected():
                print("L'utilisateur n'est pas connecté. Redirection vers l'URL d'autorisation.")
                return redirect(get_authorization_url())
            else:
                print("L'utilisateur est déjà connecté.")

                artist = form.cleaned_data.get('name')
                artist_search = spotify_search("artist", artist)
                playlist_search = spotify_search("playlist", artist)

                new_artist = form.save(commit=False)
                new_artist.biography = form.cleaned_data.get('biography')
                new_artist.name = artist_search["name"]
                new_artist.slug = slugify(new_artist.name)
                new_artist.spotify = artist_search["id"]
                new_artist.created_on = timezone.now()
                if playlist_search:
                    new_artist.playlist = playlist_search["id"]
                    
                image_url = artist_search["images"][0]["url"]
                image_response = requests.get(image_url)
                if image_response.status_code == 200:
                    image_content = ContentFile(image_response.content)
                    new_artist.thumbnail.save(f"{new_artist.name}.jpg", image_content)

                new_artist.save()

                for genre in artist_search["genres"]:
                    tag = Tag.objects.filter(slug=slugify(genre)).first()
                    if not tag:
                        tag = Tag(
                            name = genre,
                            slug=slugify(genre)
                        )
                        tag.save()
                    new_artist.tags.add(tag)

                return redirect('artists:artist', new_artist.slug)
    else:
        form = ArtistCreateForm()

    return render(request, "artists/artist_create.html", {"form": form})

@login_required
def ArtistCreateSpotifyFollowings(request):
    if not is_user_connected():
        print("L'utilisateur n'est pas connecté. Redirection vers l'URL d'autorisation.")
        global REFERER
        REFERER = request.META.get("HTTP_REFERER")
        return redirect(get_authorization_url())
    else:
        print("L'utilisateur est déjà connecté.")
        followed_artists = user_get_followed_artists()
        if followed_artists is None:
            return render(request, 'artists/error.html', {'message': 'Erreur lors de la récupération des artistes suivis.'})
        
        artists = []
        for followed_artist in followed_artists:
            if not Artist.objects.filter(slug=slugify(followed_artist['name'])).exists():
                playlist_search = spotify_search("playlist", followed_artist['name'])
                playlist = playlist_search["id"] if playlist_search else ""
                image_url = followed_artist['images'][0]['url'] if followed_artist['images'] else None
                image_content = None
                if image_url:
                    image_response = requests.get(image_url)
                    if image_response.status_code == 200:
                        image_content = ContentFile(image_response.content)
                
                artist = Artist(
                    name=followed_artist['name'],
                    slug=slugify(followed_artist['name']),
                    spotify=followed_artist['id'],
                    created_on=timezone.now(),
                    playlist=playlist,
                )
                if image_content:
                    artist.thumbnail.save(f"{followed_artist['name']}.jpg", image_content)
                artist.save()

                for genre in followed_artist["genres"]:
                    tag = Tag.objects.filter(slug=slugify(genre)).first()
                    if not tag:
                        tag = Tag(
                            name = genre,
                            slug=slugify(genre)
                        )
                        tag.save()
                    artist.tags.add(tag)

                artists.append(artist)
        return render(request, "artists/artists_list_import_confirmed.html", {"artists": artists})
    

@login_required
def ArtistFollowSpotifyFollowings(request):
    if not is_user_connected():
        print("L'utilisateur n'est pas connecté. Redirection vers l'URL d'autorisation.")
        global REFERER
        REFERER = request.META.get("HTTP_REFERER")
        return redirect(get_authorization_url())
    else:
        print("L'utilisateur est déjà connecté.")
        followed_artists = user_get_followed_artists()
        if followed_artists is None:
            return render(request, 'artists/error.html', {'message': 'Erreur lors de la récupération des artistes suivis.'})
        
        for followed_artist in followed_artists:
            if Artist.objects.filter(slug=slugify(followed_artist['name'])).exists():
                artist = get_object_or_404(Artist, slug=slugify(followed_artist['name']))
                if not artist.followers.filter(id=request.user.id).exists():
                    artist.followers.add(request.user)
                
        return render(request, "registration/user_followings.html")

    
@method_decorator(login_required, name="dispatch")
class ArtistCreateManual(CreateView):
    model = Artist
    template_name = "artists/artist_create.html"
    fields = ['name', 'biography','thumbnail','spotify','soundcloud','instagram','facebook', 'playlist']

    def form_valid(self, form):      
        form.instance.created_on = timezone.now(),
        return super().form_valid(form)
    
class ArtistsList(ListView):
    model = Artist
    context_object_name = "artists"
    template_name = "artists/artists_list.html"
    #paginate_by = 24

    def get_queryset(self):
        queryset = super().get_queryset().order_by('name')

        return queryset

@method_decorator(login_required, name="dispatch")
class ArtistUpdate(UpdateView):
    model = Artist
    template_name = "artists/artist_update.html"
    fields = ['name', 'biography','thumbnail','spotify','soundcloud','instagram','facebook', 'playlist']

class ArtistDetail(DetailView):
    model = Artist
    template_name = "artists/artist_detail.html"
    context_object_name = "artist"

@method_decorator(login_required, name="dispatch")
class ArtistDelete(DeleteView):
    model = Artist
    context_object_name = "artist"
    success_url = reverse_lazy("artists:list")

@login_required
def ArtistFollowingView(request, slug):
    context = {}
    artist = get_object_or_404(Artist, slug=slug)
    if artist.followers.filter(id=request.user.id).exists():
        artist.followers.remove(request.user)
    else:
        artist.followers.add(request.user)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

src/artists/templates/artists/artist_cards.html
{% load static %}
<div class="col row-padding artist-card">
  <a href="{% url 'artists:artist' slug=artist.slug %}">
    <div class="row container-circle">
      <div class="circle">
        {% if artist.thumbnail %}
          <img src="{{ artist.thumbnail.url }}" alt="{{ artist.title }}" />
        {% else %}
          <img src="{% get_media_prefix %}commons/users/user.png" alt="{{ artist.name }}" />
        {% endif %}
      </div>
    </div>
    <div class="row text-center name">
      <h5>{{ artist.name }}</h5>
    </div>
  </a>
</div>

src/artists/templates/artists/artist_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  <title>Supprimer: {{ artist.name }}</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'artists:list' %}">Les artistes</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'artists:artist' slug=artist.slug %}">{{ artist.name }}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Supprimer</li>
      </ol>
    </nav>
  </div>

  <div class="container">
    <div class="row margin-bottom text-center">
      <h1 class="text-center">Supprimer {{ artist.name }}</h1>
    </div>

    <div class="row row-padding col-8 mx-auto text-center">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Êtes-vous sûr de vouloir supprimer {{ artist.name }} ?</h3>
        <div class="row">{{ form }}</div>
        <div class="row row-padding">
          <input type="submit" value="Supprimer {{ artist.name }}" class="btn btn-danger" />
        </div>
      </form>
    </div>
  </div>
{% endblock %}

src/artists/templates/artists/artist_create.html
{% extends 'base.html' %}

{% block title %}
  <title>Ajouter un artiste</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'artists:list' %}">Les artistes</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Ajouter un artiste</li>
      </ol>
    </nav>
  </div>
  <div class="container">
    <div class="row margin-bottom text-center">
      <h1>Ajouter un artiste</h1>
    </div>

    <div class="row row-padding col-8 mx-auto">
      <div class="col">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">{{ form }}</div>
          <div class="row row-padding">
            <input type="submit" role="button" value="Créer" class="btn btn-submit btn-light" />
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/artists/templates/artists/artist_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>{{ artist.name }}</title>
{% endblock %}

{% block content %}
  <div class="container-fluid">
    {% if artist.thumbnail %}
      <div class="row img-bg" style="background:url('{{ artist.thumbnail.url }}'"></div>
    {% endif %}
  </div>

  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'artists:list' %}">Les artistes</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">{{ artist.name }}</li>
      </ol>
    </nav>
  </div>

  <div class="container">
    <div class="row margin-bottom text-center">
      <h1>{{ artist.name }}</h1>
    </div>
    <div class="row row-padding text-center">
      {% if artist.spotify %}
        <div class="col">
          <a href="https://open.spotify.com/intl-fr/artist/{{ artist.spotify }}"><img src="{% get_media_prefix %}commons/icons/spotify.png" alt="Spotify de {{ artist.name }}" width="30" height="30" /></a>
        </div>
      {% endif %}
      {% if artist.soundcloud %}
        <div class="col">
          <a href="{{ artist.soundcloud }}"><img src="{% get_media_prefix %}commons/icons/soundcloud.png" alt="Soundcloud de {{ artist.name }}" width="30" height="30" /></a>
        </div>
      {% endif %}
      {% if artist.instagram %}
        <div class="col">
          <a href="{{ artist.instagram }}"><img src="{% get_media_prefix %}commons/icons/instagram.png" alt="Instagram de {{ artist.name }}" width="30" height="30" /></a>
        </div>
      {% endif %}
      {% if artist.facebook %}
        <div class="col">
          <a href="{{ artist.facebook }}"><img src="{% get_media_prefix %}commons/icons/facebook.png" alt="Facebook de {{ artist.name }}" width="30" height="30" /></a>
        </div>
      {% endif %}
    </div>

    <div class="row row-padding">
      <div class="col d-grid">
        <a class="btn btn-light" href="{% url 'artists:edit' slug=artist.slug %}" role="button">Éditer</a>
      </div>
      <div class="col d-grid">
        <a class="btn btn-outline-danger" href="{% url 'artists:delete' slug=artist.slug %}" role="button">Supprimer</a>
      </div>
    </div>

    <div class="row">
      <form action="{% url 'artists:follow' slug=artist.slug %}" method="POST">
        {% csrf_token %}

        {% if request.user not in artist.followers.all %}
          <button type="submit" value="{{ artist.slug }}" class="btn btn-light"><i class="bi bi-bookmark-heart"></i> Suivre l'artiste</button>
        {% else %}
          <button type="submit" value="{{ artist.slug }}" class="btn btn-success"><i class="bi bi-bookmark-heart-fill"></i> Artiste suivi(e) !</button>
        {% endif %}

        {% if artist.followers.count > 0 %}
          <p>{{ artist.followers.count }} followers</p>
        {% endif %}
      </form>
    </div>

    <div class="row">
      <div class="clearfix">
        <h3>Biographie</h3>
        {% if artist.playlist %}
          <iframe class="col-md-6 float-md-end mb-3 ms-md-3" style="border-radius:12px" src="https://open.spotify.com/embed/playlist/{{ artist.playlist }}?utm_source=generator&theme=0" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
        {% endif %}
        <p class="justify">{{ artist.biography|safe|linebreaksbr }}</p>
      </div>
    </div>
  </div>

  <div class="container-fluid bg-light">
    <div class="container container-section">
      <div class="row row-padding">
        <h1>Sera présent(e)</h1>
      </div>

      {% if artist.events %}
        <div class="row row-padding row-cols-1 row-cols-md-4 g-4">
          {% for event in artist.events.all %}
            {% include 'events/event_cards.html' %}
          {% endfor %}
        </div>
      {% else %}
        <div class="col">
          <h5>Pas encore de date annoncée !</h5>
        </div>
      {% endif %}
    </div>
  </div>

  <div class="container-fluid bg-light">
    <div class="container container-section">
      <div class="row">
        <h1>Les commentaires</h1>
        <div class="row row-padding">
          <form action="{% url 'comments:comment' slug=artist.slug type='artist' %}" method="POST">
            {% csrf_token %}
            <div class="form-floating">
              <textarea class="form-control" placeholder="Laisser un commentaire" id="floatingTextarea2" style="height: 100px" name="comment"></textarea>
              <label for="floatingTextarea2">Laisser un commentaire</label>
            </div>
            <button type="submit" class="btn btn-light">Envoyer</button>
          </form>
        </div>
        {% if artist.comments %}
          {% for comment in artist.comments.all %}
            {% include 'comments.html' %}
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

src/artists/templates/artists/artist_update.html
{% extends 'base.html' %}

{% block title %}
  <title>Editer le profil de: {{ artist.name }}</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'artists:list' %}">Les artistes</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'artists:artist' slug=artist.slug %}">{{ artist.name }}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Editer</li>
      </ol>
    </nav>
  </div>
  <div class="container">
    <div class="row margin-bottom text-center">
      <h1>{{ artist.name }}</h1>
    </div>
    <div class="row row-padding col-8 mx-auto">
      <div class="col">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">{{ form }}</div>
          <div class="row row-padding">
            <input type="submit" role="button" value="Editer {{ artist.name }}" class="btn btn-submit btn-light" />
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/artists/templates/artists/artists_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>Les artistes du moment</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Les artistes</li>
      </ol>
    </nav>
  </div>

  <div class="container">
    <div class="row margin-bottom text-center">
      <h1>La liste des artistes</h1><p>(A-Z)</p>
    </div>
    {% if artists %}
      <div class="row row-padding margin-bottom col-6 mx-auto">
        <div class="search-container">
          <input id="search_artist" type="text" class="form-control search-input" placeholder="Rechercher..." />
          <i class="bi bi-search search-icon"></i>
        </div>
      </div>
      <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
        {% for artist in artists %}
          {% include 'artists/artist_cards.html' %}
        {% endfor %}
      </div>

      <!--                  Pagination des artistes
      <div class="row row-padding">
        <nav>
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page=1">Début</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
              </li>
            {% elif not page_obj.has_previous %}
              <li class="page-item disabled">
                <a class="page-link" href="">Début</a>
              </li>
              <li class="page-item disabled">
                <a class="page-link" href="">&laquo;</a>
              </li>
            {% endif %}

            {% for n in page_obj.paginator.page_range %}
              {% if page_obj.number == n %}
                <li class="page-item active">
                  <span class="page-link">{{ n }}<span class="sr-only"></span></span>
                </li>
              {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ n }}">{{ n }}</a>
                </li>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Fin</a>
              </li>
            {% elif not page_obj.has_next %}
              <li class="page-item disabled">
                <a class="page-link" href="">&raquo;</a>
              </li>
              <li class="page-item disabled">
                <a class="page-link" href="">Fin</a>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>                  -->
    {% else %}
      <div class="col">
        <div class="row row-padding text-center">
          <h2>Pas d'artistes pour le moment !</h2>
        </div>
      </div>
    {% endif %}
    <div class="row row-padding col-6 mx-auto">
      <a class="btn btn-light" href="{% url 'artists:create' %}" role="button">Ajouter un artiste</a>
    </div>
    <div class="row row-padding col-6 mx-auto">
      <a class="btn btn-light" href="{% url 'artists:create_spotify_followings' %}" role="button">Ajouter ses artistes suivis</a>
    </div>
    <div class="row row-padding col-6 mx-auto">
      <a class="btn btn-light" href="{% url 'artists:follow_spotify_followings' %}" role="button">Suivre ses artistes de Spotify</a>
    </div>
  </div>
{% endblock %}

src/artists/templates/artists/artists_list_import_confirmed.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>Confirmer l'import de {{ nb_artists }} artistes suivis</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'artists:list' %}">Les artistes</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Importer les artistes suivis</li>
      </ol>
    </nav>
  </div>

  <div class="container">
    <div class="row margin-bottom text-center">
      <h1>Import terminé</h1>
    </div>
    {% if artists %}
      <div class="row row-padding margin-bottom">
        <h5>L'import de {{ nb_artists }} artistes suivis s'est correctement déroulé</h5>
      </div>
      <div class="row margin-bottom">
        <h5>Artistes créés</h5>

        <table class="table table-hover">
          <tbody>
            {% for artist in artists %}
              <tr>
                <th scope="row">
                  <div class="container-circle container-circle-navbar">
                    <div class="circle">
                      {% if artist.thumbnail %}
                        <img src="{{ artist.thumbnail.url }}" alt="{{ artist.title }}" />
                      {% else %}
                        <img src="{% get_media_prefix %}commons/users/user.png" alt="{{ artist.name }}" />
                      {% endif %}
                    </div>
                  </div>
                </th>
                <td>
                  <a href="{% url 'artists:artist' slug=artist.slug %}">{{ artist.name }}</a>
                </td>
                {% if artist.tags %}
                  <td>
                    {% for tag in artist.tags.all %}
                      <span class="badge rounded-pill">{{ tag.name }}</span>
                    {% endfor %}
                  </td>
                {% endif %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <div class="col">
        <div class="row row-padding text-center">
          <h2>Aucun nouvel artiste à créer !</h2>
        </div>
      </div>
    {% endif %}
    <div class="row row-padding col-6 mx-auto">
      <a class="btn btn-light" href="{% url 'artists:create' %}" role="button">Ajouter un artiste</a>
    </div>
  </div>
{% endblock %}