src/accounts/urls.py
from django.urls import path

from .views import SignUpView, UserDetailView, UserUpdate, UserDelete, UserFollowingsView, UserInterestedView

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('<str:slug>', UserDetailView.as_view(), name='details'),
    path('<str:slug>/edit', UserUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', UserDelete.as_view(), name='delete'),
    path('<str:slug>/followings', UserFollowingsView.as_view(), name='followings'),
    path('<str:slug>/interested', UserInterestedView.as_view(), name='interested'),
]

src/artists/urls.py
from django.urls import path
from artists.views import ArtistsList, ArtistCreate, ArtistCreateSpotifyFollowings, ArtistFollowSpotifyFollowings, ArtistDelete, ArtistDetail, ArtistUpdate, ArtistFollowingView

app_name = "artists"

urlpatterns = [
    path('', ArtistsList.as_view(), name='list'),
    path('create/', ArtistCreate, name='create'),
    path('create/spotify_followings/', ArtistCreateSpotifyFollowings, name='create_spotify_followings'),
    path('follow/spotify_followings/', ArtistFollowSpotifyFollowings, name='follow_spotify_followings'),
    path('<str:slug>', ArtistDetail.as_view(), name='artist'),
    path('<str:slug>/edit', ArtistUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', ArtistDelete.as_view(), name='delete'),
    path('<str:slug>/follow', ArtistFollowingView, name='follow'),
]

src/blog/urls.py
from django.urls import path
from blog.views import BlogPostList, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete

app_name = "blog"

urlpatterns = [
    path('', BlogPostList.as_view(), name='list'),
    path('create/', BlogPostCreate.as_view(), name='create'),
    path('<str:slug>', BlogPostDetail.as_view(), name='post'),
    path('<str:slug>/edit', BlogPostUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', BlogPostDelete.as_view(), name='delete'),
]

src/comments/urls.py
from django.urls import path

from comments.views import CommentView

app_name = "comments"

urlpatterns = [
    path('<str:type>/<str:slug>/comment', CommentView, name='comment'),
]

src/events/urls.py
from django.urls import path
from events.views import EventInterestedView, EventsList, EventCreate, EventUpdate, EventDetail, EventDelete

app_name = "events"

urlpatterns = [
    path('', EventsList.as_view(), name='list'),
    path('create/', EventCreate.as_view(), name='create'),
    path('<str:slug>', EventDetail.as_view(), name='event'),
    path('<str:slug>/edit', EventUpdate.as_view(), name='edit'),
    path('<str:slug>/delete', EventDelete.as_view(), name='delete'),
    path('<str:slug>/interested', EventInterestedView, name='interested'),
]

src/nightlife/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from artists.views import spotify_callback
from events import views
from events.views import Home, Search

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('events/', include('events.urls')),
    path('artists/', include('artists.urls')),
    path('blog/', include('blog.urls')),
    path('comments/', include('comments.urls')),
    #path('tags/', include('tags.urls')),
    path('search/', views.Search, name='search'),
    path('callback/', spotify_callback, name='spotify_callback'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/events/models.py
import datetime
from django.conf import settings
from django.db import models
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.urls import reverse

from artists.models import Artist
from comments.models import Comment
from nightlife.methods import PathAndRename
from tags.models import Tag

# Create your models here.
class Event(models.Model):
    path_and_rename = PathAndRename("events/")

    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    created_on = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True)
    starts = models.DateTimeField(verbose_name="Début")
    ends = models.DateTimeField(verbose_name="Fin")
    published = models.BooleanField(default=False, verbose_name="Publié")
    is_sponsored = models.BooleanField(default=False, verbose_name="Sponsorisé")
    promoter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="promoter")
    location = models.CharField(max_length=255, null=True, blank=True, verbose_name="Localisation")
    address = models.CharField(max_length=255, null=True, blank=True, verbose_name="Adresse")
    town = models.CharField(max_length=255, null=True, blank=True, verbose_name="Ville")
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name="Prix")
    content = models.TextField(blank=True, verbose_name="Contenu")
    thumbnail = models.ImageField(blank=True, upload_to=path_and_rename)
    artists = models.ManyToManyField(Artist, related_name="events")
    interested = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="interested")
    tags = models.ManyToManyField(Tag, related_name='event_tags', blank=True)
    comments = models.ManyToManyField(Comment, related_name='event_comment', blank=True)

    class Meta:
        ordering = ["-created_on"]
        verbose_name = "Event"

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        return super().save(*args, **kwargs)
    
    #Définir la redirection
    def get_absolute_url(self):
        return reverse("events:event", kwargs={"slug": self.slug})

    def total_interested(self):
        return self.interested.count()

src/events/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

src/events/views.py
import datetime
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template.defaultfilters import slugify
from django.views.generic.edit import ModelFormMixin
from django.db.models import Count

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from accounts.models import CustomUser
from artists.models import Artist
from events.models import Event
from blog.models import BlogPost

class Home(ListView):
    model = Event
    context_object_name = "events"
    template_name = "events/home.html"

    def get_queryset(self):
        current_week = datetime.date.today().isocalendar()[1] 
        queryset = {'featured_articles': BlogPost.objects.filter(is_featured = True).order_by('-created_on')[:4],
                    'best_events_of_the_week': Event.objects.filter(starts__week=current_week, published = True).annotate(interested_count=Count('interested')).order_by('-interested_count')[:4],
                    'favourite_artists': Artist.objects.annotate(followers_count=Count('followers')).order_by('-followers_count')[:4],
                    'last_events': Event.objects.filter(published = True).order_by('-created_on')[:4],
                    'top_promoters': CustomUser.objects.annotate(events_count=Count('promoter')).order_by('-events_count')[:4]}

        return queryset


class EventsList(ListView):
    model = Event
    context_object_name = "events"
    template_name = "events/event_list.html"

    def get_queryset(self):
        queryset = {'current_events': Event.objects.filter(starts__date__gte=datetime.datetime.now(), published=True).order_by('starts'),
                    'past_events': Event.objects.filter(starts__date__lt=datetime.datetime.now(), published=True).order_by('-starts')}

        return queryset
    
@method_decorator(login_required, name="dispatch")
class EventCreate(CreateView):
    model = Event
    template_name = "events/event_create.html"
    fields = ['title', 'starts', 'ends', 'location', 'address', 'content', 'thumbnail', 'price', 'tags', 'artists']

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.promoter = self.request.user
        
        form.instance.created_on = datetime.datetime.now()
        
        return super().form_valid(form)
    

@method_decorator(login_required, name="dispatch")
class EventUpdate(UpdateView):
    model = Event
    template_name = "events/event_update.html"
    fields = ['title', 'starts', 'ends', 'location', 'address', 'content', 'thumbnail', 'price', 'tags',  'artists', 'published']

class EventDetail(DetailView):
    model = Event
    template_name = "events/event_detail.html"
    context_object_name = "event"

@method_decorator(login_required, name="dispatch")
class EventDelete(DeleteView):
    model = Event
    context_object_name = "event"
    success_url = reverse_lazy("events:list")

@login_required
def EventInterestedView(request, slug):
    context = {}
    event = get_object_or_404(Event, slug=slug)
    if event.interested.filter(id=request.user.id).exists():
        event.interested.remove(request.user)
    else:
        event.interested.add(request.user)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def Search(request):
    if request.method == 'POST':
        search_query = request.POST['search_query']
        events = Event.objects.filter(title__unaccent__icontains=search_query)
        artists = Artist.objects.filter(name__unaccent__icontains=search_query)
        blogposts = BlogPost.objects.filter(title__unaccent__icontains=search_query)
        return render(request, "events/search_results.html", {'search_query': search_query, 'events': events, 'artists': artists, 'blogposts': blogposts})
    else:
        return render(request, "events/search_results.html")

src/events/templates/events/event_cards.html
<div class="col margin-bottom">
  <div class="card h-100">
    {% if event.thumbnail %}
      <a href="{% url 'events:event' slug=event.slug %}"><img src="{{ event.thumbnail.url }}" class="card-img-top img-fluid" alt="{{ event.title }}" /></a>
    {% else %}
      <a href="{% url 'events:event' slug=event.slug %}"><div class="card-img-top img-fluid"></div></a>
    {% endif %}
    <div class="card-body">
      <div class="row">
        <div class="col">
          <div class="headline">
            <a href="{% url 'events:event' slug=event.slug %}"><h5 class="card-title">{{ event.title|title }}</h5></a>
            {% if event.is_sponsored %}
              <p class="fw-lighter fst-italic">- Sponsorisé</p>
            {% endif %}
          </div>
        </div>
        <div class="col-2">
          <form action="{% url 'events:interested' slug=event.slug %}" method="POST">
            {% csrf_token %}

            {% if request.user not in event.interested.all %}
              <button type="submit" value="{{ event.slug }}" class="btn btn"><i class="bi bi-bookmark-heart"></i></button>
            {% else %}
              <button type="submit" value="{{ event.slug }}" class="btn btn"><i class="bi bi-bookmark-heart-fill"></i></button>
            {% endif %}
          </form>
        </div>
      </div>
      <p class="card-text">{{ event.location }}</p>
      <p class="card-text">
        <small class="text-body-secondary">
          {{ event.starts }} |{% if event.price %}
            {{ event.price }}€
          {% else %}
            GRATUIT
          {% endif %}
        </small>
      </p>
      {% if event.tags %}
        {% for tag in event.tags.all %}
          <span class="badge rounded-pill">{{ tag.name }}</span>
        {% endfor %}
      {% endif %}
    </div>
  </div>
</div>

src/events/templates/events/event_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  <title>Supprimer: {{ event.title }}</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'events:list' %}">Les évènements</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'events:event' slug=event.slug %}">{{ event.title }}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Supprimer</li>
      </ol>
    </nav>
  </div>

  <div class="container">
    <div class="row margin-bottom text-center">
      <h1 class="text-center">Supprimer {{ event.title }}</h1>
    </div>

    <div class="row row-padding col-8 mx-auto text-center">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Êtes-vous sûr de vouloir supprimer {{ event.title }} ?</h3>
        <div class="row">{{ form }}</div>
        <div class="row row-padding">
          <input type="submit" value="Supprimer {{ event.title }}" class="btn btn-danger" />
        </div>
      </form>
    </div>
  </div>
{% endblock %}

src/events/templates/events/event_create.html
{% extends 'base.html' %}

{% block title %}
  <title>Créer un évènement</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'events:list' %}">Les évènements</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Créer un évènement</li>
      </ol>
    </nav>
  </div>
  <div class="container">
    <div class="row margin-bottom text-center">
      <h1>Créer un évènement</h1>
    </div>

    <div class="row row-padding col-8 mx-auto">
      <div class="col">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">{{ form }}</div>
          <div class="row row-padding">
            <input type="submit" role="button" value="Créer" class="btn btn-submit btn-light" />
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

src/events/templates/events/event_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>{{ event.title }}</title>
{% endblock %}

{% block content %}
  <div class="container-fluid">
    {% if event.thumbnail %}
      <div class="row img-bg" style="background:url('{{ event.thumbnail.url }}'"></div>
    {% endif %}
  </div>
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'events:list' %}">Les évènements</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">{{ event.title }}</li>
      </ol>
    </nav>
  </div>
  <div class="container container">
    <div class="row margin-bottom text-center">
      <div class="col">
        <h1>{{ event.title|upper }}</h1>
        <a href="{% url 'accounts:details' slug=event.promoter.username|slugify %}"><p>Par {{ event.promoter.username }}</p></a>
      </div>
    </div>
    <div class="row">
      <div class="col d-grid">
        <a class="btn btn-light" href="{% url 'events:edit' slug=event.slug %}" role="button">Éditer</a>
      </div>
      <div class="col d-grid">
        <a class="btn btn-outline-danger" href="{% url 'events:delete' slug=event.slug %}" role="button">Supprimer</a>
      </div>
    </div>

    <div class="row row-padding">
      <form action="{% url 'events:interested' slug=event.slug %}" method="POST">
        {% csrf_token %}
        {% if request.user not in event.interested.all %}
          <button type="submit" class="btn btn-light"><i class="bi bi-bookmark-heart"></i> Sauvegarder l'évènement</button>
        {% else %}
          <button type="submit" class="btn btn-success"><i class="bi bi-bookmark-heart-fill"></i> Evenement sauvegardé !</button>
        {% endif %}

        {% if event.interested.count > 0 %}
          <p>{{ event.interested.count }} intéressé(e)s</p>
        {% endif %}
      </form>
    </div>

    <div class="row">
      <h3>Les infos</h3>
      {% if event.location %}
        <p>
          <i class="bi bi-house"></i> {{ event.location }}
        </p>
      {% endif %}
      {% if event.address %}
        <p>
          <i class="bi bi-geo-alt"></i>
          {{ event.address }},{% if event.town %}
            {{ event.town }}
          {% endif %}
        </p>
      {% endif %}
      <p>
        <i class="bi bi-calendar-event"></i>
        {{ event.starts }} au {{ event.ends }} |{% if event.price %}
          {{ event.price }}€
        {% else %}
          GRATUIT
        {% endif %}
      </p>
      {% if event.tags %}
        <div class="margin-bottom">
          <h5>
            {% for tag in event.tags.all %}
              <span class="badge rounded-pill">{{ tag.name }}</span>
            {% endfor %}
          </h5>
        </div>
      {% endif %}
      <h3>Description</h3>
      <p>{{ event.content|safe|linebreaks }}</p>
    </div>
    <div class="row">
      <h1>La lineup</h1>
      {% if event.artists %}
        <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
          {% for artist in event.artists.all %}
            {% include 'artists/artist_cards.html' %}
          {% endfor %}
        </div>
      {% else %}
        <div class="col">
          <h5>Pas encore d'artistes annoncé(e)s !</h5>
        </div>
      {% endif %}
    </div>
  </div>

  <div class="container-fluid bg-light">
    <div class="container container-section">
      <div class="row">
        <h1>Les commentaires</h1>
        <div class="row row-padding">
          <form action="{% url 'comments:comment' slug=event.slug type='event' %}" method="POST">
            {% csrf_token %}
            <div class="form-floating">
              <textarea class="form-control" placeholder="Laisser un commentaire" id="floatingTextarea2" style="height: 100px" name="comment"></textarea>
              <label for="floatingTextarea2">Laisser un commentaire</label>
            </div>
            <button type="submit" class="btn btn-light">Envoyer</button>
          </form>
        </div>
        {% if event.comments %}
          {% for comment in event.comments.all %}
            {% include 'comments.html' %}
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

src/events/templates/events/event_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>Les évènements du moment</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Les évènements</li>
      </ol>
    </nav>
  </div>

  <div class="container">
    <div class="row margin-bottom text-center">
      <h1>La liste des évènements</h1>
    </div>

    <div class="row margin-bottom">
      <div class="col">
        <ul class="nav nav-pills nav-justified" id="pills-tab" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active" id="pills-current-tab" data-bs-toggle="pill" data-bs-target="#pills-current" type="button" role="tab" aria-controls="pills-current" aria-selected="true">Évènements en cours</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="pills-passed-tab" data-bs-toggle="pill" data-bs-target="#pills-passed" type="button" role="tab" aria-controls="pills-passed" aria-selected="false">Évènements passés</button>
          </li>
        </ul>
      </div>
    </div>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-current" role="tabpanel" aria-labelledby="pills-current-tab" tabindex="0">
        {% if events.current_events %}
          <div class="row row-padding row-cols-1 row-cols-sm-2 row-cols-md-4">
            {% for event in events.current_events %}
              {% include 'events/event_cards.html' %}
            {% endfor %}
          </div>
        {% else %}
          <div class="col">
            <div class="row row-padding text-center">
              <h2>Pas d'évènements pour le moment !</h2>
            </div>
          </div>
        {% endif %}
      </div>

      <div class="tab-pane fade" id="pills-passed" role="tabpanel" aria-labelledby="pills-passed-tab" tabindex="0">
        {% if events.past_events %}
          <div class="row row-padding row-cols-1 row-cols-sm-2 row-cols-md-4">
            {% for event in events.past_events %}
              {% include 'events/event_cards.html' %}
            {% endfor %}
          </div>
        {% else %}
          <div class="col">
            <div class="row row-padding text-center">
              <h2>Pas d'évènements pour le moment !</h2>
            </div>
          </div>
        {% endif %}
      </div>
    </div>

    <div class="row row-padding col-6 mx-auto">
      <a class="btn btn-light" href="{% url 'events:create' %}" role="button">Ajouter un évènement</a>
    </div>
  </div>
{% endblock %}

src/events/templates/events/event_update.html
{% extends 'base.html' %}

{% block title %}
  <title>Editer: {{ event.title }}</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'events:list' %}">Les évènements</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'events:event' slug=event.slug %}">{{ event.title }}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Editer</li>
      </ol>
    </nav>
  </div>
  <div class="container">
    <div class="row margin-bottom text-center">
      <h1 class="text-center">{{ event.title }}</h1>
    </div>

    <div class="row row-padding col-8 mx-auto">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">{{ form }}</div>
        <div class="row row-padding">
          <input type="submit" role="button" value="Créer" class="btn btn-submit btn-light" />
        </div>
      </form>
    </div>
  </div>
{% endblock %}

src/events/templates/events/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>Nightlife</title>
{% endblock %}

{% block content %}
  {% if events.featured_articles %}
    {% include 'events/home_carrousel.html' %}
  {% endif %}

  <div class="container-fluid">
    <div class="container container-section">
      <div class="row row-padding">
        <h1>Les évènements les plus populaires de la semaine</h1>
      </div>
      <div class="row row-padding row-cols-1 row-cols-sm-2 row-cols-md-4">
        {% for event in events.best_events_of_the_week %}
          {% include 'events/event_cards.html' %}
        {% endfor %}
      </div>
      <div class="row row-padding col-6 mx-auto">
        <a class="btn btn-light" href="{% url 'events:list' %}" role="button">Voir tous les évènements</a>
      </div>
    </div>
  </div>

  <div class="container-fluid bg-light">
    <div class="container container-section">
      <div class="row row-padding">
        <h1>Les artistes du moment</h1>
      </div>
      <div class="row row-padding row-cols-1 row-cols-sm-2 row-cols-md-4">
        {% for artist in events.favourite_artists %}
          {% include 'artists/artist_cards.html' %}
        {% endfor %}
      </div>
      <div class="row row-padding col-6 mx-auto">
        <a class="btn btn-outline-secondary" href="{% url 'artists:list' %}" role="button">Voir tous les artistes</a>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="container container-section">
      <div class="row row-padding">
        <h1>Les derniers évènements créés</h1>
      </div>
      <div class="row row-padding row-cols-1 row-cols-sm-2 row-cols-md-4">
        {% for event in events.last_events %}
          {% include 'events/event_cards.html' %}
        {% endfor %}
      </div>
      <div class="row row-padding col-6 mx-auto">
        <a class="btn btn-light" href="{% url 'events:list' %}" role="button">Voir tous les évènements</a>
      </div>
    </div>
  </div>

  <div class="container-fluid bg-light">
    <div class="container container-section">
      <div class="row row-padding">
        <h1>Nos top créateurs</h1>
      </div>
      <div class="row row-padding row-cols-1 row-cols-sm-2 row-cols-md-4">
        {% for user in events.top_promoters %}
          {% include 'registration/user_cards.html' %}
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

src/events/templates/events/home_carrousel.html
{% load static %}
<div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    {% for article in events.featured_articles %}
      {% if forloop.first %}
        <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="{{ forloop.counter0 }}" class="active" aria-current="true"></button>
      {% else %}
        <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="{{ forloop.counter0 }}"></button>
      {% endif %}
    {% endfor %}
  </div>


  <div class="carousel-inner">

    {% for article in events.featured_articles %}
      {% if forloop.first %}
        <div class="carousel-item active" data-bs-interval="10000">
      {% else %}
        <div class="carousel-item" data-bs-interval="2000">
      {% endif %}

        <div class="carousel-caption d-none d-md-block margin-bottom">
            <a href="{% url 'blog:post' slug=article.slug %}">
                <h1>{{ article.title|upper }}</h1>
                {% if article.summary %}
                  <p>{{ article.summary|truncatewords_html:20}}</p>
                {% else %}
                  <p>{{ article.content|truncatewords_html:20}}</p>
                {% endif %}
            </a>
        </div>

      {% if article.thumbnail %}
       <img src="{{ article.thumbnail.url }}" class="d-block w-100" alt="{{ article.title }}" />
      {% endif %}
        </div>
    {% endfor %}
    </div>
    
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

src/events/templates/events/search_results.html
{% extends 'base.html' %}

{% block title %}
  <title>Résultats de recherche:</title>
{% endblock %}

{% block content %}
  <div class="container breadcrumbs-section">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'home' %}">Accueil</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
          {% if search_query %}
            Résultats de la recherche: "{{ search_query }}"
          {% else %}
            Erreur de recherche
          {% endif %}
        </li>
      </ol>
    </nav>
  </div>
  <div class="container container-section">
    <div class="row margin-bottom text-center">
      {% if search_query %}
        <h1>Résultats de la recherche: "{{ search_query }}"</h1>
      {% else %}
        <h1>Erreur de recherche</h1>
      {% endif %}
    </div>

    <div class="row row-padding">
      {% if search_query %}
        {% if events %}
          <h2 class="text-center">Évènements:</h2>
          <div class="row row-padding row-cols-1 row-cols-sm-2 row-cols-md-4">
            {% for event in events %}
              {% include 'events/event_cards.html' %}
            {% endfor %}
          </div>
        {% endif %}
        {% if artists %}
          <h2 class="text-center">Artistes:</h2>
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">
            {% for artist in artists %}
              {% include 'artists/artist_cards.html' %}
            {% endfor %}
          </div>
        {% endif %}
        {% if blogposts %}
          <h2 class="text-center">Articles:</h2>
          <div class="row row-padding row-cols-1 row-cols-sm-2 row-cols-md-4">
            {% for post in blogposts %}
              {% include 'blog/blogpost_cards.html' %}
            {% endfor %}
          </div>
        {% endif %}
        {% if not events and not artists and not blogposts %}
          <h2 class="text-center">Désolé, aucun résultat trouvé !</h2>
          <div class="row row-padding col-6 mx-auto">
            <a class="btn btn-light" href="{% url 'home' %}" role="button">Retour à la page d'accueil</a>
          </div>
        {% endif %}
      {% else %}
        <h2 class="text-center">Veuillez saisir votre recherche dans la barre ci-dessus</h2>
        <div class="row row-padding col-6 mx-auto">
          <a class="btn btn-light" href="{% url 'home' %}" role="button">Retour à la page d'accueil</a>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}